[package]
name = "rust-complex"
version = "0.1.0"
authors = ["Fernando Herrero Carrón <fernando@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.3.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
